-- AlterTable
ALTER TABLE "address" ALTER COLUMN "postal-code" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "staying-since" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "city" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "company" ALTER COLUMN "annual-income" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "business-type" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "department" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "employee-no" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "employee-type" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "income-date" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "income-type" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "occupation-category" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "position" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "tel-code" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "tel-no" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "country" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "customer" ALTER COLUMN "car-plate" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "gender" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "ic" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "marital-status" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "mobile-no" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "passport" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "race" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "tel-code" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "tel-no" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "customer_relation" ALTER COLUMN "gender" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "ic" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "mobile-no" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "passport" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "relationship" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "state" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "username" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(255);
